apiVersion: v1
kind: Service
metadata:
  name: {{ include "privacy-pools-relayer.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "privacy-pools-relayer.labels" . | nindent 4 }}
{{- if .Values.annotations }}
  annotations:
    {{- .Values.annotations | toYaml | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.sessionAffinity }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- end }}
  ports:
    - port: {{ .Values.service.ports.number }}
      name: {{ .Values.service.ports.name }}
      targetPort: {{ .Values.service.ports.name }}
      nodePort: null
  selector:
    app.kubernetes.io/component: web
    app.kubernetes.io/instance: {{ include "privacy-pools-relayer.name" . }}
    app.kubernetes.io/name: {{ .Release.Name }}
