## @section Common parameters
##

## @param nameOverride String to partially override common.names.fullname
##
nameOverride: ""
## @param fullnameOverride String to fully override common.names.fullname
##
fullnameOverride: ""

## @param replicas Replicas for relayer
##

replicas: 1

## @param strategy Strategy for deployment
##
strategy: "RollingUpdate"

## @param commonLabels [object] Labels to add to all related objects
##
commonLabels: {}

## @param annotations [object] Annotations to to all related objects
##
annotations: {}

## @param nodeSelector Object containing node selection constraint to deployment
## https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector
##
nodeSelector: {}

## @param resources Resource specification to deployment
##
resources:
  relayer:
    limits:
      cpu: 2
      memory: 2G
    requests:
      cpu: 1
      memory: 1G

## @param tolerations Tolerations specifications to deployment
##
tolerations: []

## @param affinity Affinity specifications to deployment
##
affinity: {}

persistence:
  ## @param persistence.storageClassName StorageClassName to be used
  ##
  storageClassName:

  ## @param persistence.accessModes List of AccessModes to the Volume
  ##
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany

  ## @param persistence.size Volume size
  ##
  size: 1Gi

image:
  ## @param image.registry Docker registry to deployment
  ##
  registry: registry.hub.docker.com

  ## @param image.repository Docker image repository to deployment
  ##
  repository: privacy-pools/relayer

  ## @param image.tag Docker image tag to deployment
  ##
  tag: latest

  ## @param image.pullPolicy Pull policy to deployment as deinfed in
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: Always

service:
  ## @param service.type service type
  ##
  type: ClusterIP
  ports:
    ## @param service.ports.number service port number
    ##
    number: 80
    ## @param service.ports.name service port name
    ##
    name: nginx
  ## @param service.sessionAffinity Control where client requests go, to the same pod or round-robin
  ## Values: ClientIP or None
  ## ref: https://kubernetes.io/docs/user-guide/services/
  ##
  sessionAffinity: None

ingress:
  ## @param ingress.ingressClassName Name of the ingress class name to be used
  ##
  ingressClassName: ""

  ## @param ingress.hostname Default host for the ingress record
  ##
  hostname: privacy-pools-relayer.local

  ## @param ingress.annotations Annotations to be added to ingress resources
  ## @skipingress.annotations
  ##
  annotations: {}

## @section Configuration Parameters
##
config:
  ## @param config.secretReferenceKey Reference to an existing secret containing the following entries: PRIVATE_KEY, PINATA_SECRET_API_KEY, PINATA_API_KEY
  secretReferenceKey: ""

  ## @param config.port application backend port
  port: ""

  ## @param config.chain_id chain identifier to use
  chain_id: ""

  ## @param config.rpc_url Ethereum RPC endpoint
  rpc_url: ""

  ## @param config.reward_address address which receives rewards
  reward_address: ""

  ## @param config.confirmations number of blocks until a block is considered safe
  confirmations: ""

  ## @param config.max_gas_price upper limit for gas price
  max_gas_price: ""

  ## @param config.transfer_service_fee set fee by the relayer
  transfer_service_fee: ""

  ## @param config.withdrawal_service_fee set fee by the relayer
  withdrawal_service_fee: ""

  redis:
    ## @param config.redis.secretReferenceKey Reference to an existing secret containing the following entries: REDIS_URL
    # Format redis://<pass>@privacy-pools-relayer-redis.privacy-pools-relayer.svc.cluster.stage:6379
    secretReferenceKey: ""
    ## @param config.redis.username Redis username
    username: default
    ## @param config.redis.password Redis user's password
    password: ""
    ## @param config.redis.database Redis database number
    database: 0
    ## @param config.redis.host Redis server host
    host: ""
    ## @param config.redis.port Redis server port
    port: "6379"
    ## @param config.redis.storageClassName StorageClassName
    storageClassName: ""
